# fly.toml app configuration file generated for scuffed-mmorpg on 2025-03-09T15:09:31-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'scuffed-mmorpg'
primary_region = 'sjc'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
dockerfile = 'Dockerfile'

[env]
NODE_ENV = 'production'
PORT = '3001'

[http_service]
internal_port = 3001
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[http_service.concurrency]
type = 'connections'
hard_limit = 1000
soft_limit = 500

# Enable WebSocket support for signaling
[[http_service.ports]]
port = 80
handlers = ["http", "websocket"]
force_https = true

[[http_service.ports]]
port = 443
handlers = ["tls", "http", "websocket"]

[http_service.tcp_checks]
interval = "15s"
timeout = "2s"
grace_period = "1s"

# UDP ports for WebRTC (geckos.io)
[[services]]
protocol = 'udp'
internal_port = 10000
processes = ['app']

[[services.ports]]
port = 10000
range = 100

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[[metrics]]
port = 9091
path = '/metrics'
https = false
