app = "scuffed-mmorpg"
primary_region = "sjc" # Silicon Valley
kill_signal = "SIGINT"
kill_timeout = 5

[build]
dockerfile = "Dockerfile"

[env]
PORT = "3001"
NODE_ENV = "production"

[http_service]
internal_port = 3001
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[http_service.concurrency]
type = "connections"
hard_limit = 1000
soft_limit = 500

[[http_service.ports]]
port = 80
handlers = ["http"]
force_https = true

[[http_service.ports]]
port = 443
handlers = ["tls", "http"]

[http_service.tcp_checks]
interval = "15s"
timeout = "2s"
grace_period = "1s"

# UDP ports for WebRTC (geckos.io)
[[services]]
protocol = "udp"
internal_port = 10000
processes = ["app"]

[[services.ports]]
port = 10000
range = 10100

[static]
guest_path = "/app/packages/game/dist"
url_prefix = "/"

[metrics]
port = 9091
path = "/metrics"
